---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: r_os_servers

- name: Delete instances
  os_server:
    state: absent
    name: "{{ __delete_osp_instance.name }}"
  loop: "{{ r_os_servers.openstack_servers }}"
  loop_control:
    loop_var: __delete_osp_instance
      
    
   
