---
- name: Smoke test playbook
  hosts: workstation
  gather_facts: false

  tasks:

  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: frontend
    register: r_front_result
    tags:
      - osp.smoke

  - debug: 
      msg: "{{ r_front_result.openstack_servers }}"
    tags:
      - osp.smoke

  - name: Curl website
    uri:
      url: "http://frontend"
      return_content: yes
      status_code: 200
    register: webpage
    delegate_to: localhost
    tags:
      - osp.smoke
  

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
