---
- name: Install {{ payload }} package
  yum:
    name: "{{ payload }}"
    state: latest

- name: Create tomcat {{ tomact_web_root }}  directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Copy static index.html to {{ tomcat_web_root}}
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: '0644'
  notify: restart {{ payload }}

- name: enable and start tomcat
  service:
    name: "{{ payload }}"
    state: started
    enabled: true

